networks:
  copilot-net:
    driver: bridge

volumes:
  chroma-data:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - INTERNAL_API_URL=http://backend:8000
        - NEXT_PUBLIC_API_URL=http://54.89.238.13:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://54.89.238.13:8000
      - INTERNAL_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - copilot-net
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      - chromadb
    networks:
      - copilot-net
    restart: unless-stopped
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  chromadb:
    image: chromadb/chroma:0.5.5
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - copilot-net
    restart: unless-stopped
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
